// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1/ocr.proto

package ocr_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on OCRFile with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *OCRFile) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for FileId

	// no validation rules for Language

	// no validation rules for Status

	// no validation rules for Text

	// no validation rules for Properties

	return nil
}

// OCRFileValidationError is the validation error returned by OCRFile.Validate
// if the designated constraints aren't met.
type OCRFileValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OCRFileValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OCRFileValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OCRFileValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OCRFileValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OCRFileValidationError) ErrorName() string { return "OCRFileValidationError" }

// Error satisfies the builtin error interface
func (e OCRFileValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOCRFile.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OCRFileValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OCRFileValidationError{}

// Validate checks the field values on OcrRequest with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *OcrRequest) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetReferenceId()); l < 3 || l > 40 {
		return OcrRequestValidationError{
			field:  "ReferenceId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_OcrRequest_ReferenceId_Pattern.MatchString(m.GetReferenceId()) {
		return OcrRequestValidationError{
			field:  "ReferenceId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	if l := utf8.RuneCountInString(m.GetLanguageId()); l < 2 || l > 3 {
		return OcrRequestValidationError{
			field:  "LanguageId",
			reason: "value length must be between 2 and 3 runes, inclusive",
		}
	}

	if !_OcrRequest_LanguageId_Pattern.MatchString(m.GetLanguageId()) {
		return OcrRequestValidationError{
			field:  "LanguageId",
			reason: "value does not match regex pattern \"[a-z]{2,3}\"",
		}
	}

	// no validation rules for Properties

	// no validation rules for Async

	if l := len(m.GetFileId()); l < 1 || l > 5 {
		return OcrRequestValidationError{
			field:  "FileId",
			reason: "value must contain between 1 and 5 items, inclusive",
		}
	}

	for idx, item := range m.GetFileId() {
		_, _ = idx, item

		if l := utf8.RuneCountInString(item); l < 3 || l > 40 {
			return OcrRequestValidationError{
				field:  fmt.Sprintf("FileId[%v]", idx),
				reason: "value length must be between 3 and 40 runes, inclusive",
			}
		}

		if !_OcrRequest_FileId_Pattern.MatchString(item) {
			return OcrRequestValidationError{
				field:  fmt.Sprintf("FileId[%v]", idx),
				reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
			}
		}

	}

	return nil
}

// OcrRequestValidationError is the validation error returned by
// OcrRequest.Validate if the designated constraints aren't met.
type OcrRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OcrRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OcrRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OcrRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OcrRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OcrRequestValidationError) ErrorName() string { return "OcrRequestValidationError" }

// Error satisfies the builtin error interface
func (e OcrRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOcrRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OcrRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OcrRequestValidationError{}

var _OcrRequest_ReferenceId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

var _OcrRequest_LanguageId_Pattern = regexp.MustCompile("[a-z]{2,3}")

var _OcrRequest_FileId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")

// Validate checks the field values on OcrResponse with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *OcrResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for ReferenceId

	for idx, item := range m.GetResult() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return OcrResponseValidationError{
					field:  fmt.Sprintf("Result[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// OcrResponseValidationError is the validation error returned by
// OcrResponse.Validate if the designated constraints aren't met.
type OcrResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OcrResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OcrResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OcrResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OcrResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OcrResponseValidationError) ErrorName() string { return "OcrResponseValidationError" }

// Error satisfies the builtin error interface
func (e OcrResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOcrResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OcrResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OcrResponseValidationError{}

// Validate checks the field values on StatusRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *StatusRequest) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetReferenceId()); l < 3 || l > 40 {
		return StatusRequestValidationError{
			field:  "ReferenceId",
			reason: "value length must be between 3 and 40 runes, inclusive",
		}
	}

	if !_StatusRequest_ReferenceId_Pattern.MatchString(m.GetReferenceId()) {
		return StatusRequestValidationError{
			field:  "ReferenceId",
			reason: "value does not match regex pattern \"[0-9a-z_-]{3,20}\"",
		}
	}

	return nil
}

// StatusRequestValidationError is the validation error returned by
// StatusRequest.Validate if the designated constraints aren't met.
type StatusRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StatusRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StatusRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StatusRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StatusRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StatusRequestValidationError) ErrorName() string { return "StatusRequestValidationError" }

// Error satisfies the builtin error interface
func (e StatusRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStatusRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StatusRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StatusRequestValidationError{}

var _StatusRequest_ReferenceId_Pattern = regexp.MustCompile("[0-9a-z_-]{3,20}")
